//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeHost.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Z:/_Aegis_Non_Phase/12172020_DVD_Delivery/AEGIS-MDL-MEDIA000042/Models</string>
  <string>Z:/Aegis_Phase 0/AEgis_Phase 0_Rev.A/Models</string>
  <string>Z:/Aegis_Phase 1/AEgis_Phase 1_Rev.A/Models</string>
  <string>Z:/Aegis_Phase 1/AEgis_Phase 1_Rev.C/2020-05-07-01-aegis-cm2-models-phase1/Models</string>
  <string>Z:/Aegis_Phase 2/AEgis_Phase 2_Rev.A/AEGIS-MDL-MEDIA000026/Models</string>
  <string>Z:/Aegis_Phase 2/AEgis_Phase 2_Rev.B/AEGIS-MDL_MEDIA000026/Models</string>
  <string>Z:/Aegis_Phase 2/AEgis_Phase 2_Rev.B/AEGIS-MDL-MEDIA000029/Models</string>
  <string>Z:/Aegis_Phase 3/AEgis_Phase 3_Rev.A/AEGIS-MDL-MEDIA000034/Models</string>
  <string>Z:/Aegis_Phase 3/AEgis_Phase 3_Rev.B/AEGIS-MDL-MEDIA000034/Models</string>
  <string>Z:/Aegis_Phase 4/AEgis_Phase 4_Rev.A/AEGIS-MDL-MEDIA000042/Models</string>
  <string>Z:/Aegis_Phase 4/AEgis_Phase 4_Rev.B/AEGIS-MDL-MEDIA000045/Models</string>
  <string>D:/Models</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ContentReferences {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ContentReferences"]));
            }
            set {
                this["ContentReferences"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>D:/proj/moov/moov.html</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AppReferences {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AppReferences"]));
            }
            set {
                this["AppReferences"] = value;
            }
        }
    }
}
